---
- hosts: jenkins-slave
  become: true
  tasks:
  - name: update ubuntu repos
    apt:
      update_cache: true
      force_apt_get: true
      cache_valid_time: 3600
  
  - name: install docker
    apt:
      name: docker.io
      state: present
  
  - name: start docker service
    service:
      name: docker
      state: started
      enabled: yes